# -*- coding: utf-8 -*-
"""task2_socialmediapostgenerator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nKMlnku4TU3IiX1kyH-_lzUomPayHDUv
"""

import requests
import json

GROQ_API_KEY = "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"
GROQ_MODEL = "llama-3.1-8b-instant"
GROQ_URL = "https://api.groq.com/openai/v1/chat/completions"



PLATFORM_STYLES = {
    "linkedin": "Professional, insightful, and value-driven. Can be a bit longer "
                 "(3-6 sentences). Use 1-2 relevant hashtags at the end. No emojis, "
                 "or at most one.",
    "twitter": "Short, punchy, and attention-grabbing. Max 280 characters. "
               "Casual tone, can use 1-3 hashtags and 1-2 emojis.",
    "instagram": "Friendly, visual, and engaging. Use emojis naturally throughout. "
                  "Include a short caption (2-4 sentences) plus 5-8 relevant hashtags "
                  "at the end."
}


def call_groq(prompt, temperature=0.7):
    headers = {
        "Authorization": f"Bearer {GROQ_API_KEY}",
        "Content-Type": "application/json"
    }
    data = {
        "model": GROQ_MODEL,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": temperature
    }
    response = requests.post(GROQ_URL, headers=headers, json=data)
    response.raise_for_status()
    return response.json()["choices"][0]["message"]["content"]


def clean_json(raw_text):
    raw_text = raw_text.replace("```json", "").replace("```", "").strip()
    return json.loads(raw_text)


# ============== FEATURE 1 & 2: Single post generator (with platform tone) ==============
def generate_post(topic, platform):
    platform = platform.lower()
    style = PLATFORM_STYLES.get(platform, PLATFORM_STYLES["linkedin"])

    prompt = f"""Write ONE social media post about this topic/keyword: "{topic}"

Platform: {platform}
Style rules for this platform: {style}

Reply with ONLY the post text, nothing else (no explanations, no quotation marks around it)."""

    post = call_groq(prompt)
    return post.strip()


# ============== FEATURE 3: Content calendar from a brand description ==============
def generate_content_calendar(brand_description, platform, num_days=7):
    platform = platform.lower()
    style = PLATFORM_STYLES.get(platform, PLATFORM_STYLES["linkedin"])

    prompt = f"""You are a social media strategist.

Brand/product description: "{brand_description}"
Platform: {platform}
Style rules for this platform: {style}

Create a {num_days}-day content calendar. For each day, pick a different
content angle (e.g. educational, behind-the-scenes, testimonial, promo,
tip, question to audience, fun fact) so the calendar feels varied, then
write the actual ready-to-post caption for that angle.

Reply ONLY in this exact JSON format, nothing else, no markdown fences:
{{
  "calendar": [
    {{"day": 1, "angle": "...", "post": "..."}},
    {{"day": 2, "angle": "...", "post": "..."}}
  ]
}}"""

    raw = call_groq(prompt, temperature=0.8)
    try:
        result = clean_json(raw)
    except json.JSONDecodeError:
        result = {"calendar": [{"day": "?", "angle": "raw output", "post": raw}]}
    return result["calendar"]


if __name__ == "__main__":

    TOPIC = "5 tips for staying productive while working from home"
    BRAND_DESCRIPTION = ("EcoBrew - a sustainable coffee brand that sells "
                          "compostable coffee pods and donates 1% of profits "
                          "to reforestation projects.")
    PLATFORM = "instagram"          # linkedin / twitter / instagram
    CALENDAR_DAYS = 5
    # -----------------------------

    print("=" * 60)
    print(f"SINGLE POST  |  Topic: {TOPIC}  |  Platform: {PLATFORM}")
    print("=" * 60)
    single_post = generate_post(TOPIC, PLATFORM)
    print(single_post)

    print("\n" + "=" * 60)
    print(f"{CALENDAR_DAYS}-DAY CONTENT CALENDAR  |  Platform: {PLATFORM}")
    print("=" * 60)
    calendar = generate_content_calendar(BRAND_DESCRIPTION, PLATFORM, CALENDAR_DAYS)

    for day in calendar:
        print(f"\nDay {day['day']} - {day['angle']}")
        print(day["post"])
        print("-" * 60)