# -*- coding: utf-8 -*-
"""task1_emailgenerator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nKMlnku4TU3IiX1kyH-_lzUomPayHDUv
"""

import requests
import json


GROQ_API_KEY = "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"
GROQ_MODEL = "llama-3.1-8b-instant"
GROQ_URL = "https://api.groq.com/openai/v1/chat/completions"



incoming_emails = [
    {
        "from": "ali.raza@example.com",
        "subject": "Question about pricing plans",
        "body": "Hi, I wanted to know if you offer a student discount on your "
                "premium plan. Also, does it support multiple users?"
    },
    {
        "from": "fatima.k@example.com",
        "subject": "Very disappointed with my order",
        "body": "I ordered a product 10 days ago and it still hasn't arrived. "
                "This is unacceptable, I want a refund immediately."
    },
    {
        "from": "hamza.dev@example.com",
        "subject": "App keeps crashing on login",
        "body": "Every time I try to log in to the app, it crashes right after "
                "the splash screen. I'm using Android 13. Please help."
    },
    {
        "from": "sara.malik@example.com",
        "subject": "Do you ship internationally?",
        "body": "Hello, I'm based in Dubai. Do you ship to the UAE, and how "
                "long does delivery usually take?"
    },
]


# ============== STEP 2: Quick keyword-based category guess ==============

def keyword_category(text):
    text = text.lower()

    complaint_words = ["disappointed", "refund", "unacceptable", "complain",
                        "angry", "bad experience", "worst", "terrible"]
    support_words = ["crash", "error", "bug", "not working", "issue",
                      "problem", "help", "broken", "doesn't work"]

    if any(word in text for word in complaint_words):
        return "complaint"
    if any(word in text for word in support_words):
        return "support"
    return "inquiry"  # default if nothing matches


# ============== STEP 3: Ask the LLM to confirm category + write a reply ==============
def generate_ai_reply(email, guessed_category):
    prompt = f"""You are a helpful customer support assistant replying to a customer email.

Email from: {email['from']}
Subject: {email['subject']}
Body: {email['body']}

A quick keyword check guessed the category as: "{guessed_category}"

Do two things:
1. Confirm or correct the category. It must be exactly one of: inquiry, complaint, support.
2. Write a short, polite, professional reply (3-5 sentences) addressing the email directly.

Reply ONLY in this exact JSON format, nothing else, no markdown:
{{"category": "...", "reply": "..."}}"""

    headers = {
        "Authorization": f"Bearer {GROQ_API_KEY}",
        "Content-Type": "application/json"
    }
    data = {
        "model": GROQ_MODEL,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.4
    }

    response = requests.post(GROQ_URL, headers=headers, json=data)
    response.raise_for_status()
    raw_text = response.json()["choices"][0]["message"]["content"]

    # Strip ```json fences in case the model adds them
    raw_text = raw_text.replace("```json", "").replace("```", "").strip()

    try:
        result = json.loads(raw_text)
    except json.JSONDecodeError:
        result = {"category": guessed_category, "reply": raw_text}

    return result



def run_email_responder():
    print("=" * 60)
    print("AI EMAIL RESPONDER - Processing Inbox")
    print("=" * 60)

    for i, email in enumerate(incoming_emails, start=1):
        guessed = keyword_category(email["subject"] + " " + email["body"])
        result = generate_ai_reply(email, guessed)

        print(f"\nEmail #{i}")
        print(f"From     : {email['from']}")
        print(f"Subject  : {email['subject']}")
        print(f"Category : {result['category']}")
        print(f"Draft Reply:\n{result['reply']}")
        print("-" * 60)


if __name__ == "__main__":
    run_email_responder()